spring.application.name=ms-clientes
server.port=8082

# Conexión a DB (Crea la base de datos 'servimel_db' en XAMPP si no existe)
spring.datasource.url=jdbc:mysql://localhost:3306/servimel_db
spring.datasource.username=root
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/